### ISSUE TITLE
work for an a2000?

### ISSUE THREAD

**Issue by ogg1e** [jbilander/Amiga_DB23_video_adapter#2]
I'm assuming this won't work in an a2000? I believe these need to be buffered to work in an a2000.

**Comment by jbilander** [comment]
Hi,

It'll work will all Amigas, no problem. It is buffered with a 74HCT2G17 chip for V-Sync and H-Sync. Buffering is only when you make a VGA-cable with this PCB which in turn requires a 15 KHz compatible monitor. If you make a SCART-cable with this PCB which is also possible to do then you use C-Sync and no buffering is needed but rather you put a resistor to attenuate the signal.
